name: Bug Report
description: 請描述問題
title: "[Bug] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 問題描述  
        請清楚描述遇到的問題。

  - type: textarea
    id: steps
    attributes:
      label: 重現步驟
      description: 請列出操作步驟
      placeholder: |
        1. ...
        2. ...

  - type: textarea
    id: expected
    attributes:
      label: 預期行為
      description: 說明你原本預期會發生的結果

  - type: textarea
    id: additional
    attributes:
      label: 補充資訊
      description: 包含裝置型號、瀏覽器版本、環境設定等（如有）
