name: Homework CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Step 1 - Check file
        run: cat file.txt

      - name: Step 2 - Check for "error"
        run: |
          if grep -q "error" file.txt; then
            echo "Fail"
            exit 1
          else
            echo "Success"
          fi